- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Unarchive backend dist
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/backend
    
- name: Install Node modules
  shell: |
    cd /home/ubuntu/backend
    npm install

- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
