- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Transfer backend zip to cloud server
  copy:
    src: /root/project/backend/dist.tar.gz
    dest: /home/ubuntu/backend

- name: Unarchive backend dist
  become: true
  unarchive:
    src: /root/project/backend/dist.tar.gz
    dest: /home/ubuntu/backend
    
- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
