
- name: Unarchive backend dist
  become: true
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu
    
- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/backend
    ls
    pm2 start npm --name backend -- start
